---
apiVersion: "kubeflow.org/v1alpha2"
kind: TFJob
metadata:
  name: kube-demo-dist
spec:
  tfReplicaSpecs:
    Master:
      replicas: 1
      template:
        spec:
          containers:
          - name: tensorflow
            image: alvinhenrick/kube-demo-dist:1.1
            command: ["python", "/code/train_and_eval.py","--output_path=/model/imdb_model"]
            volumeMounts:
            - name: data
              mountPath: "/data"
            - name: models
              mountPath: "/model"
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: mydata
          - name: models
            persistentVolumeClaim:
              claimName: mymodels
    Worker:
      replicas: 3
      template:
        spec:
          containers:
          - name: tensorflow
            image: alvinhenrick/kube-demo-dist
            command: ["python", "/code/train_and_eval.py","--output_path=/model/imdb_model"]
            volumeMounts:
            - name: data
              mountPath: "/data"
            - name: models
              mountPath: "/model"
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: mydata
          - name: models
            persistentVolumeClaim:
              claimName: mymodels
    PS:
      replicas: 2
      template:
        spec:
          containers:
          - name: tensorflow
            image: alvinhenrick/kube-demo-dist
            command: ["python", "/code/train_and_eval.py","--output_path=/model/imdb_model"]
            volumeMounts:
            - name: data
              mountPath: "/data"
            - name: models
              mountPath: "/model"
            ports:
            - containerPort: 6006
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: mydata
          - name: models
            persistentVolumeClaim:
              claimName: mymodels
